spring:
  application:
    name: auth-template
  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/test}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: ${JWT_SECRET:c42a6f73b7586cd49089c3a6f2e61250cd8fec2573bfb45b5f5f6e06b1395b86}
  expired:
    access: 3600
    refresh: 300000

oauth2:
  google:
    client-id:
      ios: ${GOOGLE_CLIENT_ID_IOS}
      web: ${GOOGLE_CLIENT_ID_WEB}
    client-secret: ${GOOGLE_CLIENT_SECRET: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}
